name: CI - Code Testing Workflow

on:
  pull_request:
    branches:
      - develop
      - main
      - "feature/*"
      - "hotfix/*"
    paths:
      - "src/**"
      - "tests/**"
  push:
    branches:
      - main
      - develop
    paths:
      - "src/**"
      - "tests/**"

jobs:
  test:
    name: Run Tests and Generate Coverage Report
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m venv venv                     # Create a virtual environment
          source venv/bin/activate                # Activate the virtual environment
          pip install -r requirements.txt         # Install required dependencies
          pip install pytest pytest-cov           # Add coverage tools

      # Step 4: Run tests with coverage
      - name: Run tests with coverage
        run: |
          source venv/bin/activate                # Ensure the virtual environment is active
          pytest --cov=src --cov-report=xml --cov-report=term

      # Step 5: Post coverage summary as PR comment
      - name: Post coverage summary as PR comment
        if: github.event_name == 'pull_request'
        uses: machine-learning-apps/pytest-coverage-comment@v1.0.0
        with:
          pytest-cov-path: coverage.xml
